apiVersion: v1
kind: Service

metadata:
  namespace: my-app
  name: my-app-service
  labels:
    name: my-app

spec:
  selector:
    name: my-app

  type: NodePort

  ports:
    - name: www
      protocol: TCP
      port: 8080
      targetPort: 80
