apiVersion: networking.k8s.io/v1
kind: NetworkPolicy

metadata:
  namespace: my-app
  name: my-app-policy

spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy

metadata:
  namespace: my-app
  name: my-app-database-policy

spec:
  podSelector:
    matchLabels:
      name: database
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              name: backend

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy

metadata:
  namespace: my-app
  name: my-app-webserver-policy

spec:
  podSelector:
    matchLabels:
      name: webserver
  policyTypes:
    - Ingress
  ingress:
    - from:
      - ipBlock:
          cidr: 0.0.0.0/0