apiVersion: v1
kind: Namespace
metadata:
  name: my-app-ns

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: my-app-ns
  name: my-app-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: my-app-ns
  name: my-app-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: my-app-ns
  name: my-app-rolebinding
subjects:
  - kind: ServiceAccount
    name: my-app-sa
    namespace: my-app-ns
roleRef:
  kind: Role
  name: my-app-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: Pod
metadata:
  name: my-app-pod
  namespace: my-app-ns
spec:
  serviceAccountName: my-app-sa
  containers:
    - name: my-app-nginx-container
      image: nginx
      resources:
        requests:
          cpu: "100m"
          memory: "64Mi"
        limits:
          cpu: "200m"
          memory: "128Mi"
      ports:
        - name: www
          containerPort: 80
