apiVersion: v1
kind: ConfigMap

metadata:
  namespace: my-app
  name: my-app-config

data:
  APP_ENV: production
  LOG_LEVEL: info
  CONFIG_JSON: |
    {
      "debug": false,
      "max_connections": 100
    }

---
apiVersion: v1
kind: Pod

metadata:
  namespace: my-app
  name: my-app

spec:
  volumes:
    - name: config-volume
      configMap:
        name: my-app-config

  containers:
    - name: my-nginx-container
      image: nginx:latest
      resources:
        requests:
          memory: 64Mi
          cpu: 250m
        limits:
          memory: 128Mi
          cpu: 500m
      envFrom:
        - configMapRef:
            name: my-app-config
      volumeMounts:
        - name: config-volume
          mountPath: /etc/config
