apiVersion: v1
kind: LimitRange

metadata:
  namespace: my-app
  name: my-app-limitrange

spec:
  limits:
    - type: Container
      max:
        cpu: "1000m"
        memory: 2Gi
      min:
        cpu: 100m
        memory: 256Mi
      default:
        cpu: 500m
        memory: 512Mi
      defaultRequest:
        cpu: 250m
        memory: 256Mi
