apiVersion: storage.k8s.io/v1
kind: StorageClass

metadata:
  name: my-app-storage
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
reclaimPolicy: Retain
volumeBindingMode: Immediate

---
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: my-app-pvc
  
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: my-app-storage
  resources:
    requests:
      storage: 10Gi
